### ISSUE TITLE
Add files usually needed in open source projects

### ISSUE THREAD

**Issue by xavierfigueroav** [enmanuel-mag/MiHorarioWeb#14]
Hi. This projects lacks some files that are found in most of the open source projects out there.

These files may help newcomers to start using and contributing to this project.

Based on information at [opensource.guide](https://opensource.guide/), I made the following checklist:

- [x] **LICENSE**: An open source license guarantees that others can use, copy, modify, and contribute back to your project without repercussions. It also protects you from sticky legal situations.
- [x] **README**: It explains how to use your project. It also explains why your project matters, and what your users can do with it. 
- [x] **CONTRIBUTING**: It tells your audience how to participate in your project.
- [x] **CODE OF CONDUCT**: It helps set ground rules for behavior for your project’s participants.
- [x] **CONTRIBUTORS**: It lists everyone who’s contributed to your project.

Fortunately, you already have some of them, which I have checked. For the rest, I can contribute by adding them, but I would need your feedback @enmanuel-mag @jcoboss, specially for the LICENSE file: choose a license from [here](https://choosealicense.com/) and tell me which you chose to add the file.

Feel free to add new items to the checklist.

**Comment by xavierfigueroav** [comment]
I have opened a PR to add the CONTRIBUTORS file. @enmanuel-mag @jcoboss, please review.

**Comment by xavierfigueroav** [comment]
@enmanuel-mag Please, choose a license from [here](https://choosealicense.com) and tell me which you chose to add the file.

**Comment by enmanuel-mag** [comment]
@xavierfigueroav I choosed the GPLv3 license

**Comment by enmanuel-mag** [comment]
> @enmanuel-mag Please, choose a license from [here](https://choosealicense.com) and tell me which you chose to add the file.

I choose the GPLv3 license.

**Comment by xavierfigueroav** [comment]
@enmanuel-mag Please, review the PR and merge if ok.

**Comment by xavierfigueroav** [comment]
Are you fan of any open source project or community from which to base MiHorarioWeb's CODE OF CONDUCT? If not, I can search and suggest one.

**Comment by xavierfigueroav** [comment]
I've opened a PR containing a CODE OF CONDUCT file. Please, review @enmanuel-mag.

**Comment by enmanuel-mag** [comment]
> I've opened a PR containing a CODE OF CONDUCT file. Please, review @enmanuel-mag.

Good I'll check it

**Comment by xavierfigueroav** [comment]
Great! Since every item from the list has been checked, I think this issue can be closed.
